### ISSUE TITLE
web version requires `scriptjs` which is not a dependency

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/apple-sign-in#29]
`require('scriptjs')` in the code, but this is no dependency. Took me a long time to find this bug 😅

**Comment by JayJay666** [comment]
After install plugin with `npm install @capacitor-community/apple-sign-in` have a problem with WEB implementation. 

If I call `registerWebPlugin(SignInWithApple);` make error in every devices

> ./node_modules/@capacitor-community/apple-sign-in/dist/esm/web.js
> Module not found: Error: Can't resolve 'scriptjs' in '/Users/jakub_josef_forman/Development/pwa/cocktails/node_modules/@capacitor-community/apple-sign-in/dist/esm'

The problem is not in dependency as you say.

Have ani hot fix for enable implementation on Web? 

Implementation without using `registerWebPlugin(SignInWithApple);` work fine on iOS.

**Comment by mesqueeb** [comment]
Yes. I have the same. I tried adding the dependency but it's not enough. 

WEB just doesn't work at all for me. 

Now I have commented out the registerWeb line and have given up for now.
I hope someone can fix it !

**Comment by epicshaggy** [comment]
solved in #20
